-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 11:10:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `books` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `books` ;

-- -----------------------------------------------------
-- Table `books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `books` ;

CREATE TABLE IF NOT EXISTS `books` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authors` ;

CREATE TABLE IF NOT EXISTS `authors` (
  `id` INT NOT NULL,
  `author_name` VARCHAR(45) NULL,
  `books_id` INT NOT NULL,
  PRIMARY KEY (`id`, `books_id`),
  CONSTRAINT `fk_authors_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_has_books` ;

CREATE TABLE IF NOT EXISTS `users_has_books` (
  `users_user_id` INT NOT NULL,
  `books_book_id` INT NOT NULL,
  PRIMARY KEY (`users_user_id`, `books_book_id`),
  CONSTRAINT `fk_users_has_books_users`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books_books1`
    FOREIGN KEY (`books_book_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratings` ;

CREATE TABLE IF NOT EXISTS `ratings` (
  `tconst` INT NOT NULL,
  `average_rating` VARCHAR(55) NULL,
  `number_of_votes` VARCHAR(55) NULL,
  PRIMARY KEY (`tconst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_basics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `title_basics` ;

CREATE TABLE IF NOT EXISTS `title_basics` (
  `tconst` INT NOT NULL,
  `primary_title` VARCHAR(55) NULL,
  `start_year` VARCHAR(55) NULL,
  `runtime` VARCHAR(55) NULL,
  `ratings_tconst` INT NOT NULL,
  PRIMARY KEY (`tconst`, `ratings_tconst`),
  CONSTRAINT `fk_title_basics_ratings1`
    FOREIGN KEY (`ratings_tconst`)
    REFERENCES `mydb`.`ratings` (`tconst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `genre_id` INT NOT NULL,
  `genre_name` VARCHAR(55) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `title_genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`title_genres` (
  `title_basics_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `genres_genre_id`),
  CONSTRAINT `fk_title_basics_has_genres_title_basics1`
    FOREIGN KEY (`title_basics_tconst`)
    REFERENCES `mydb`.`title_basics` (`tconst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_title_basics_has_genres_genres1`
    FOREIGN KEY (`genres_genre_id`)
    REFERENCES `mydb`.`genres` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `` ;

CREATE TABLE IF NOT EXISTS `` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `title_genres` ;

CREATE TABLE IF NOT EXISTS `title_genres` (
  `title_basics_tconst` INT NOT NULL,
  `genres_genre_id` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `genres_genre_id`),
  CONSTRAINT `fk_title_basics_has_genres_title_basics1`
    FOREIGN KEY (`title_basics_tconst`)
    REFERENCES `mydb`.`title_basics` (`tconst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_title_basics_has_genres_genres1`
    FOREIGN KEY (`genres_genre_id`)
    REFERENCES `mydb`.`genres` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`title_basics_has_ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `title_basics_has_ratings` ;

CREATE TABLE IF NOT EXISTS `title_basics_has_ratings` (
  `title_basics_tconst` INT NOT NULL,
  `ratings_tconst` INT NOT NULL,
  PRIMARY KEY (`title_basics_tconst`, `ratings_tconst`),
  CONSTRAINT `fk_title_basics_has_ratings_title_basics1`
    FOREIGN KEY (`title_basics_tconst`)
    REFERENCES `mydb`.`title_basics` (`tconst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_title_basics_has_ratings_ratings1`
    FOREIGN KEY (`ratings_tconst`)
    REFERENCES `mydb`.`ratings` (`tconst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`favorites` ;

CREATE TABLE IF NOT EXISTS `favorites` (
  `users_id` INT NULL,
  `books_id` INT NULL,
  CONSTRAINT `fk_users_has_books1_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_books1_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
